//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acerpro.Ui.AcerproService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfArrayOfCountryCurrencyDtoNGKS6tMi", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfArrayOfCountryCurrencyDtoNGKS6tMi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerpro.Ui.AcerproService.CountryCurrencyDto[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerpro.Ui.AcerproService.CountryCurrencyDto[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeField, value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryCurrencyDto", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Entities.Concreate.Dtos")]
    [System.SerializableAttribute()]
    public partial class CountryCurrencyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapitalCityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CapitalCityName {
            get {
                return this.CapitalCityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CapitalCityNameField, value) != true)) {
                    this.CapitalCityNameField = value;
                    this.RaisePropertyChanged("CapitalCityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName {
            get {
                return this.CurrencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyNameField, value) != true)) {
                    this.CurrencyNameField = value;
                    this.RaisePropertyChanged("CurrencyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfCountryCurrencyDtoNGKS6tMi", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfCountryCurrencyDtoNGKS6tMi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerpro.Ui.AcerproService.CountryCurrencyDto ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerpro.Ui.AcerproService.CountryCurrencyDto Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeField, value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryCurrencyCreateDto", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Entities.Concreate.Dtos")]
    [System.SerializableAttribute()]
    public partial class CountryCurrencyCreateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CapitalCityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CapitalCityName {
            get {
                return this.CapitalCityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CapitalCityNameField, value) != true)) {
                    this.CapitalCityNameField = value;
                    this.RaisePropertyChanged("CapitalCityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName {
            get {
                return this.CurrencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyNameField, value) != true)) {
                    this.CurrencyNameField = value;
                    this.RaisePropertyChanged("CurrencyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfArrayOfCountryCodeAndNameDtoJLzdrnDW", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfArrayOfCountryCodeAndNameDtoJLzdrnDW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerpro.Ui.AcerproService.CountryCodeAndNameDto[] ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerpro.Ui.AcerproService.CountryCodeAndNameDto[] Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeField, value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryCodeAndNameDto", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Entities.Concreate.Dtos.ServiceDt" +
        "os")]
    [System.SerializableAttribute()]
    public partial class CountryCodeAndNameDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISOCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISOCode {
            get {
                return this.ISOCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ISOCodeField, value) != true)) {
                    this.ISOCodeField = value;
                    this.RaisePropertyChanged("ISOCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfCurrencyDtoJLzdrnDW", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfCurrencyDtoJLzdrnDW : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerpro.Ui.AcerproService.CurrencyDto ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerpro.Ui.AcerproService.CurrencyDto Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeField, value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyDto", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Entities.Concreate.Dtos.ServiceDt" +
        "os")]
    [System.SerializableAttribute()]
    public partial class CurrencyDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISOCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISOCode {
            get {
                return this.ISOCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ISOCodeField, value) != true)) {
                    this.ISOCodeField = value;
                    this.RaisePropertyChanged("ISOCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResultOfstring", Namespace="http://schemas.datacontract.org/2004/07/Acerpro.Wcf")]
    [System.SerializableAttribute()]
    public partial class ServiceResultOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultTypeField, value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcerproService.ICountryCurrency")]
    public interface ICountryCurrency {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/Get", ReplyAction="http://tempuri.org/ICountryCurrency/GetResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCurrencyDtoNGKS6tMi Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/Get", ReplyAction="http://tempuri.org/ICountryCurrency/GetResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCurrencyDtoNGKS6tMi> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/GetById", ReplyAction="http://tempuri.org/ICountryCurrency/GetByIdResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/GetById", ReplyAction="http://tempuri.org/ICountryCurrency/GetByIdResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/Save", ReplyAction="http://tempuri.org/ICountryCurrency/SaveResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi Save(Acerpro.Ui.AcerproService.CountryCurrencyCreateDto createDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/Save", ReplyAction="http://tempuri.org/ICountryCurrency/SaveResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi> SaveAsync(Acerpro.Ui.AcerproService.CountryCurrencyCreateDto createDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/Update", ReplyAction="http://tempuri.org/ICountryCurrency/UpdateResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi Update(Acerpro.Ui.AcerproService.CountryCurrencyDto updateDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/Update", ReplyAction="http://tempuri.org/ICountryCurrency/UpdateResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi> UpdateAsync(Acerpro.Ui.AcerproService.CountryCurrencyDto updateDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/GetCountryList", ReplyAction="http://tempuri.org/ICountryCurrency/GetCountryListResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCodeAndNameDtoJLzdrnDW GetCountryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/GetCountryList", ReplyAction="http://tempuri.org/ICountryCurrency/GetCountryListResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCodeAndNameDtoJLzdrnDW> GetCountryListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/CountryCurrency", ReplyAction="http://tempuri.org/ICountryCurrency/CountryCurrencyResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfCurrencyDtoJLzdrnDW CountryCurrency(string countryIsoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/CountryCurrency", ReplyAction="http://tempuri.org/ICountryCurrency/CountryCurrencyResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCurrencyDtoJLzdrnDW> CountryCurrencyAsync(string countryIsoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/CapitalCity", ReplyAction="http://tempuri.org/ICountryCurrency/CapitalCityResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfstring CapitalCity(string countryIsoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/CapitalCity", ReplyAction="http://tempuri.org/ICountryCurrency/CapitalCityResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfstring> CapitalCityAsync(string countryIsoCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/CountryIsoCode", ReplyAction="http://tempuri.org/ICountryCurrency/CountryIsoCodeResponse")]
        Acerpro.Ui.AcerproService.ServiceResultOfstring CountryIsoCode(string countryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICountryCurrency/CountryIsoCode", ReplyAction="http://tempuri.org/ICountryCurrency/CountryIsoCodeResponse")]
        System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfstring> CountryIsoCodeAsync(string countryName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICountryCurrencyChannel : Acerpro.Ui.AcerproService.ICountryCurrency, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountryCurrencyClient : System.ServiceModel.ClientBase<Acerpro.Ui.AcerproService.ICountryCurrency>, Acerpro.Ui.AcerproService.ICountryCurrency {
        
        public CountryCurrencyClient() {
        }
        
        public CountryCurrencyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CountryCurrencyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountryCurrencyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CountryCurrencyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCurrencyDtoNGKS6tMi Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCurrencyDtoNGKS6tMi> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi Save(Acerpro.Ui.AcerproService.CountryCurrencyCreateDto createDto) {
            return base.Channel.Save(createDto);
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi> SaveAsync(Acerpro.Ui.AcerproService.CountryCurrencyCreateDto createDto) {
            return base.Channel.SaveAsync(createDto);
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi Update(Acerpro.Ui.AcerproService.CountryCurrencyDto updateDto) {
            return base.Channel.Update(updateDto);
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCountryCurrencyDtoNGKS6tMi> UpdateAsync(Acerpro.Ui.AcerproService.CountryCurrencyDto updateDto) {
            return base.Channel.UpdateAsync(updateDto);
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCodeAndNameDtoJLzdrnDW GetCountryList() {
            return base.Channel.GetCountryList();
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfArrayOfCountryCodeAndNameDtoJLzdrnDW> GetCountryListAsync() {
            return base.Channel.GetCountryListAsync();
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfCurrencyDtoJLzdrnDW CountryCurrency(string countryIsoCode) {
            return base.Channel.CountryCurrency(countryIsoCode);
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfCurrencyDtoJLzdrnDW> CountryCurrencyAsync(string countryIsoCode) {
            return base.Channel.CountryCurrencyAsync(countryIsoCode);
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfstring CapitalCity(string countryIsoCode) {
            return base.Channel.CapitalCity(countryIsoCode);
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfstring> CapitalCityAsync(string countryIsoCode) {
            return base.Channel.CapitalCityAsync(countryIsoCode);
        }
        
        public Acerpro.Ui.AcerproService.ServiceResultOfstring CountryIsoCode(string countryName) {
            return base.Channel.CountryIsoCode(countryName);
        }
        
        public System.Threading.Tasks.Task<Acerpro.Ui.AcerproService.ServiceResultOfstring> CountryIsoCodeAsync(string countryName) {
            return base.Channel.CountryIsoCodeAsync(countryName);
        }
    }
}
